# Count of networks to generate
networks count: 10
# Number of pure clients per network
network peers: 2
# Max number of gateways in network (min is 1)
max gateways: 1
# Max other networks connected to one's gateway
max gateway connectivity: 3