networks:
  network1:
    driver: bridge
  network2:
    driver: bridge
services:
  node1:
    build: .
    command: python ./node.py
    container_name: node1
    networks:
    - network1
    - network2
    volumes:
    - ./conf-node1.yml:/node/config.yml
  node2:
    build: .
    command: python ./node.py
    container_name: node2
    networks:
    - network1
    volumes:
    - ./conf-node2.yml:/node/config.yml
  node3:
    build: .
    command: python ./node.py
    container_name: node3
    networks:
    - network1
    volumes:
    - ./conf-node3.yml:/node/config.yml
  node4:
    build: .
    command: python ./node.py
    container_name: node4
    networks:
    - network2
    - network1
    volumes:
    - ./conf-node4.yml:/node/config.yml
  node5:
    build: .
    command: python ./node.py
    container_name: node5
    networks:
    - network2
    volumes:
    - ./conf-node5.yml:/node/config.yml
  node6:
    build: .
    command: python ./node.py
    container_name: node6
    networks:
    - network2
    volumes:
    - ./conf-node6.yml:/node/config.yml
version: '3'
 