version: "3"

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge

services:

  node1:
    build: .
    command: python ./node.py
    container_name: node1
    volumes:
      - ./conf-node1.yml:/node/config.yml
    networks:
      - network1
      - network2
  node2:
    build: .
    command: python node.py
    container_name: node2
    volumes:
      - ./conf-node2.yml:/node/config.yml
    networks:
      - network1
  node3:
    build: .
    command: python node.py
    container_name: node3
    volumes:
      - ./conf-node3.yml:/node/config.yml
    networks:
      - network1
  node4:
    build: .
    command: python ./node.py
    container_name: node4
    volumes:
      - ./conf-node4.yml:/node/config.yml
    networks:
      - network2
      - network1
  node5:
    build: .
    command: python node.py
    container_name: node5
    volumes:
      - ./conf-node5.yml:/node/config.yml
    networks:
      - network2
  node6:
    build: .
    command: python node.py
    container_name: node6
    volumes:
      - ./conf-node6.yml:/node/config.yml
    networks:
      - network2



node1 [172.19.0.5] - exit_node=True
node4 [172.19.0.4] - exit_node=True
node3 [172.19.0.2]
node2 [172.19.0.3]
node5 [172.20.0.2]
node6 [172.20.0.3]


node5    | Table: [('172.20.0.3', 35751), ('172.20.0.2', 40265)]
node6    | 
node6    | Table: [('172.20.0.2', 40265), ('172.20.0.3', 35751)]
node6 exited with code 0
node5 exited with code 0
node1    | 
node1    | Table: [('172.20.0.3', 35751), ('172.20.0.2', 40265), ('172.19.0.2', 59819), ('172.19.0.3', 47237), ('172.19.0.4', 44963), ('172.19.0.5', 55714)]
node2    | 
node2    | Table: [('172.19.0.4', 44963), ('172.19.0.5', 55714), ('172.19.0.2', 59819), ('172.19.0.3', 47237)]
node3    | 
node3    | Table: [('172.19.0.3', 47237), ('172.19.0.4', 44963), ('172.19.0.5', 55714), ('172.19.0.2', 59819)]
node4    | 
node4    | Table: [('172.19.0.5', 55714), ('172.20.0.3', 35751), ('172.20.0.2', 40265), ('172.19.0.2', 59819), ('172.19.0.3', 47237), ('172.19.0.4', 44963)]