version: '3'

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge
  network3:
    driver: bridge

services:

  node-network1:
    build: .
    command: python ./node.py
    networks:
      - network1
    volumes:
    - ./artefacts/:/node/artefacts/

  node-network2:
    build: .
    command: python ./node.py
    networks:
      - network2
    volumes:
    - ./artefacts/:/node/artefacts/

  node-network3:
    build: .
    command: python ./node.py
    networks:
      - network3
    volumes:
    - ./artefacts/:/node/artefacts/

  node-network1-network2:
    build: .
    command: python ./node.py
    networks:
    - network1
    - network2
    volumes:
    - ./artefacts/:/node/artefacts/

  node-network2-network3:
    build: .
    command: python ./node.py
    networks:
    - network2
    - network3
    volumes:
    - ./artefacts/:/node/artefacts/
