networks:
  network1:
    driver: bridge
  network2:
    driver: bridge
  network3:
    driver: bridge
  # network4:
  #   driver: bridge
services:
  node1:
    build: .
    command: python ./node.py
    container_name: node1
    networks:
    - network1
    - network2
    volumes:
    - ./conf-node1.yml:/node/config.yml
    - ./artefacts:/node/artefacts/
  # node10:
  #   build: .
  #   command: python ./node.py
  #   container_name: node10
  #   networks:
  #   - network4
  #   volumes:
  #   - ./conf-node10.yml:/node/config.yml
  #   - ./artefacts:/node/artefacts/
  # node11:
  #   build: .
  #   command: python ./node.py
  #   container_name: node11
  #   networks:
  #   - network3
  #   - network4
  #   volumes:
  #   - ./conf-node11.yml:/node/config.yml
  #   - ./artefacts:/node/artefacts/
  # node12:
  #   build: .
  #   command: python ./node.py
  #   container_name: node12
  #   networks:
  #   - network1
  #   - network4
  #   volumes:
  #   - ./conf-node12.yml:/node/config.yml
  #   - ./artefacts:/node/artefacts/
  # node13:
  #   build: .
  #   command: python ./node.py
  #   container_name: node13
  #   networks:
  #   - network4
  #   volumes:
  #   - ./conf-node13.yml:/node/config.yml
  #   - ./artefacts:/node/artefacts/
  node2:
    build: .
    command: python ./node.py
    container_name: node2
    networks:
    - network1
    volumes:
    - ./conf-node2.yml:/node/config.yml
    - ./artefacts:/node/artefacts/
  node3:
    build: .
    command: python ./node.py
    container_name: node3
    networks:
    - network1
    volumes:
    - ./conf-node3.yml:/node/config.yml
    - ./artefacts:/node/artefacts/
  node4:
    build: .
    command: python ./node.py
    container_name: node4
    networks:
    - network2
    - network1
    volumes:
    - ./conf-node4.yml:/node/config.yml
    - ./artefacts:/node/artefacts/
  node5:
    build: .
    command: python ./node.py
    container_name: node5
    networks:
    - network2
    volumes:
    - ./conf-node5.yml:/node/config.yml
    - ./artefacts:/node/artefacts/
  node6:
    build: .
    command: python ./node.py
    container_name: node6
    networks:
    - network2
    volumes:
    - ./conf-node6.yml:/node/config.yml
    - ./artefacts:/node/artefacts/
  node7:
    build: .
    command: python ./node.py
    container_name: node7
    networks:
    - network3
    volumes:
    - ./conf-node7.yml:/node/config.yml
    - ./artefacts:/node/artefacts/
  node8:
    build: .
    command: python ./node.py
    container_name: node8
    networks:
    - network3
    - network2
    volumes:
    - ./conf-node8.yml:/node/config.yml
    - ./artefacts:/node/artefacts/
  node9:
    build: .
    command: python ./node.py
    container_name: node9
    networks:
    - network3
    volumes:
    - ./conf-node9.yml:/node/config.yml
    - ./artefacts:/node/artefacts/
version: '3'
