version: "3"

networks:
  network1:
    driver: bridge
  network2:
    driver: bridge

services:

  node1:
    build: .
    command: python ./node.py
    container_name: node1
    volumes:
      - ./conf-node1.yml:/node/config.yml
    networks:
      - network1
      - network2
  node2:
    build: .
    command: python node.py
    container_name: node2
    volumes:
      - ./conf-node2.yml:/node/config.yml
    networks:
      - network1
  node3:
    build: .
    command: python node.py
    container_name: node3
    volumes:
      - ./conf-node3.yml:/node/config.yml
    networks:
      - network1
  node4:
    build: .
    command: python ./node.py
    container_name: node4
    volumes:
      - ./conf-node4.yml:/node/config.yml
    networks:
      - network2
      # - network1
  node5:
    build: .
    command: python node.py
    container_name: node5
    volumes:
      - ./conf-node5.yml:/node/config.yml
    networks:
      - network2
  node6:
    build: .
    command: python node.py
    container_name: node6
    volumes:
      - ./conf-node6.yml:/node/config.yml
    networks:
      - network2
